arsspot/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog'), name='blog_app'),
    url(r'^$', views.home, name='home'),
]

admin.site.site_header = "Блог"

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post-list'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^posts/(?P<slug>[\w-]+)/$', views.post_detail, name='post-detail'),
    url(r'^page/(?P<page>[\d]+)/$', views.post_list, name='page'),
    url(r'^tag/(?P<tag>[\w-]+)/$', views.post_list, name='tag'),
    url(r'^about/$', views.about, name='about'),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.text import slugify
from unidecode import unidecode
from django.utils import timezone
from markdown2 import markdown
from django.utils.safestring import mark_safe


def upload_location(instance, filename):
    return 'blog/{}/{}'.format(instance.slug, filename)


def make_title(text):
    _list = text.split()
    res = ' '.join([word.capitalize() for word in _list])
    return res


class Tag(models.Model):
    name = models.CharField(max_length=35, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120, unique=True)
    sub_title = models.CharField(max_length=300, blank=True)
    slug = models.SlugField(unique=True, blank=True)
    tag = models.ManyToManyField(Tag, blank=True, related_name='related_posts')
    content = models.TextField()
    draft = models.BooleanField(default=False)
    timestamp = models.DateTimeField(default=timezone.now)
    view_counter = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.title = make_title(self.title)
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    def content_html(self):
        content = self.content
        return mark_safe(markdown(content, extras=['fenced-code-blocks', 'tables',
                                                   'wiki-tables']))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post-detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-draft", "-timestamp"]



class Feedback(models.Model):
    email = models.EmailField()
    message = models.TextField()
    replied = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['replied', 'timestamp']

    def __str__(self):
        return self.email

home/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Feedback
from django.forms import ModelForm


class FeedbackForm(ModelForm):

    class Meta:
        model = Feedback
        exclude = ('replied',)
        widgets = {
            'message': forms.Textarea(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'message': 'Сообщение:',
            'email': 'Ваш e-mail:'
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage
from .models import Post
from .forms import FeedbackForm
from django.shortcuts import redirect
from django.contrib import messages
from django.http import Http404


def post_list(request, page=1, tag=None):
    queryset = Post.objects.all()
    if not request.user.is_staff or not request.user.is_superuser:
        queryset = queryset.filter(draft=False)
    if tag:
        queryset = queryset.filter(tag__name=tag)
    paginator = Paginator(queryset, 10)
    try:
        posts = paginator.page(page)
    except EmptyPage:
        raise Http404
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, slug):
    queryset = Post.objects.all()
    if not request.user.is_staff or not request.user.is_superuser:
        queryset = queryset.filter(draft=False)
    post = get_object_or_404(queryset, slug=slug)
    if post:
        post.view_counter += 1
        post.save()
    return render(request, 'blog/post_detail.html', {'post': post})


def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ваше сообщение успешно доставлено!')
            return redirect('blog:feedback')
    else:
        form = FeedbackForm()
    return render(request, 'blog/feedback.html', {'form': form})


def about(request):
    return render(request, 'blog/about.html')

home/views.py
from django.shortcuts import render
from django.shortcuts import redirect


def home(request):
    return redirect('blog:post-list')

blog/templates/blog/_meta_post.html
    {% load static %}
    <link rel="canonical" href="{{request.build_absolute_uri}}" />
    <title>{{post.title}} - Arsen Arutiunian</title>
    <meta name="description" content="{% if post.sub_title|length < 200 %}{{post.sub_title}}{% else %}{{post.sub_title|slice:'190'}}...{% endif %}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="{{post.title}} - Arsen Arutiunian.">
    <meta property="og:description" content="{% if post.sub_title|length < 200 %}{{post.sub_title}}{% else %}{{post.sub_title|slice:'190'}}...{% endif %}" />
    <meta property="og:site_name" content="Arsen Arutiunian - Про Python, Django и веб-разработку." />

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block meta %}
    <title>Обо мне - Arsen Arutiunian</title>
    <meta name="description" content="Меня зовут Арсен Арутюнян. Вот уже как несколько лет увлекаюсь Python и относительно недавно веб-разработкой. Сюда, буду писать преимущественно о Python, Django и веб-разработке." />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Обо мне - Arsen Arutiunian.">
    <meta property="og:description" content="Меня зовут Арсен Арутюнян. Вот уже как несколько лет увлекаюсь Python и относительно недавно веб-разработкой. Сюда в блог, буду писать преимущественно о Python, Django и веб-разработке." />
    <meta property="og:site_name" content="Arsen Arutiunian - Про Python, Django и веб-разработку." />
{% endblock %}

{% block content %}
<h2 class="text-left">Обо мне</h2>
<hr>
<p class="n">Меня зовут Арсен Арутюнян. Вот уже как несколько лет увлекаюсь Python и относительно недавно веб-разработкой. Живу в Краснодаре. Сюда, буду писать преимущественно о Python, Django и веб-разработке.</p>
<br>
<p>Важно! В своих постах, ни разу не претендую на истину в последней инстанции, так что смело оставляйте свои комментарии если есть что добавить или спросить, обсудим. Всегда интересно посмотреть на другие подходы и опыт, делитесь.</p>
<br>
<p>«Изучил что-то — пробуй это объяснить, пока не поймёшь сам»</p>
<br>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ru-RU" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block meta %}    
    <title>Arsen Arutiunian - Про Python, Django и веб-разработку</title>
    <meta name="description" content="Блог Арсена Арутюняна о Python, Django и веб-разработке." />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Arsen Arutiunian - Про Python, Django и веб-разработку.">    
    <meta property="og:description" content="Блог Арсена Арутюняна. Про Python, Django и веб-разработку." />
    <meta property="og:site_name" content="Arsen Arutiunian - Про Python, Django и веб-разработку." />    
    {% endblock %}
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:image" content="http://{{request.get_host}}{% static 'img/og.jpg' %}" />
    <meta property="og:image:width" content="640" />
    <meta property="og:image:height" content="355" />
    <meta property="og:locale" content="ru_RU" />
    <meta property="fb:admins" content="https://www.facebook.com/arsen.arutyunyan">
    <meta property="fb:app_id" content="739245509575707">
    <link rel="canonical" href="{{request.build_absolute_uri}}" />

    <!-- CSS -->
    <link rel="icon" type="image/png" href="{% static "img/favicon.png" %}">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/arsspot-blog.css" %}" rel="stylesheet">
    <link href="{% static "css/pygments.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">




    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class='language-python'>
    <!-- Navigation -->
    <nav class="nav navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> <!-- 
                    Menu  --><i class="fa fa-bars"> </i>
                </button>
                <a class="navbar-brand" href="{% url 'blog:post-list' %}"><strong>Arsen Arutiunian</strong></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:post-list' %}">Блог</a>
                    </li>                    
                    <li>
                        <a href="{% url 'blog:feedback' %}">Контакт</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:about' %}">Обо мне</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Main Content -->
    <div class="container">
        <div class="row">            
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            {% block content %}
                
            {% endblock %}                
            </div>
        </div>
    </div>
    <hr>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="text-right footer-text">2017 © Arsen Arutiunian</div>
                </div>

            </div>
        </div>
    </footer>

    
    <!-- jQuery -->
    <script src="{% static "js/jquery.min.js" %}"></script>    
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block js %}
    {% endblock %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-92666837-1', 'auto');
      ga('send', 'pageview');
    </script>

    <!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter43065249 = new Ya.Metrika({
                    id:43065249,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/43065249" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</body>
</html>

blog/templates/blog/feedback.html
{% extends 'blog/base.html' %}
{% load static %}
{% block meta %}
    <link rel="canonical" href="{{request.build_absolute_uri}}" />
    <title>Контакт - Arsen Arutiunian</title>
    <meta name="description" content="Cвязаться со мной. Форма обратной связи." />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Контакт - Arsen Arutiunian.">
    <meta property="og:description" content="Cвязаться со мной. Форма обратной связи." />
    <meta property="og:site_name" content="Arsen Arutiunian - Про Python, Django и веб-разработку." />
{% endblock %}

{% block content %}
<h2 class="text-left">Напишите мне!</h2>
<hr>
<p>Приветствую!</p>
<br>
<p class="n">Вопросы, предложения, замечания, идеи, либо просто сказать "привет" — можно через форму ниже.</p>
<hr>
<div class="col-lg-6 col-md-6 col-sm-6 nopadding">
<form action="{% url 'blog:feedback' %}" method="post">
{% csrf_token %}
{% for hidden in form.hidden_fields %}
  {{ hidden }}
{% endfor %}

{% if messages %}
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

{% for field in form.visible_fields %}
    {% for error in field.errors %}
      <div class="alert alert-danger alert-dismissible" role="alert">      
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ error }}
      </div>
    {% endfor %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {{ field }}    
  </div>
{% endfor %}

  <button type="submit" class="btn btn-default">Отправить</button>
</form>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block meta %}
	{% include 'blog/_meta_post.html' %}
{% endblock %}
{% block content %}
<h1 class="text-center title">{{post.title}}</h1>
    <hr>
    <p style="text-align: right; color: grey; font-style: italic; font-size: 1.4rem; margin-bottom: 2rem;">опубликовано: {{post.timestamp| date:"M d, Y" }}</p>
    <div class="post-content">{{post.content_html}}</div>
    <br>
    {% for tag in post.tag.all %} <a href="{% url 'blog:tag' tag %}" class="label label-info">{{tag}}</a>{% endfor %}
    <br>
    <br>

<hr style="border-style: dashed; border-color: #E1E1E1;" />
{% if not post.draft %}
<div id="comments">
    <div id="disqus_thread"></div>
    <script>
        var disqus_config = function () {
            this.page.url = '{{request.build_absolute_uri}}';
            this.page.identifier = '{{request.path}}';
        };
        
        (function() {  
            var d = document, s = d.createElement('script');
            
            s.src = '//arsspot-blog.disqus.com/embed.js';  
            
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
  
        <div class="post-in-list col-md-12 nopadding">
        <div class="col-md-2"><span class="date">{{ post.timestamp | date:"M d, Y" }}</span></div>
        <div class="col-md-10">{% if post.draft %}<span style="color: red;">DRAFT ! </span>{% endif %} 
                                <a class="post_link" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                {% if post.sub_title %} — <span class="sub_title">{{post.sub_title|safe}}</span>{% endif %}
        </div>
        </div>                    
    {% endfor %}

    {% if posts.has_other_pages %}
    <div class="paginator col-md-12 text-center">
        {% if posts.has_previous %}
            <a href={% if posts.previous_page_number == 1 %}"{% url 'blog:post-list' %}"
                            {% else %}
                                "{% url 'blog:page' posts.previous_page_number %}"
                    {% endif %}><< сюда</a> &emsp;-&emsp;<i>{{posts.number}}</i>&emsp;-&emsp;
        {% else %}<span class="disabled"><< сюда</span> &emsp;-&emsp;<i>{{posts.number}}</i>&emsp;-&emsp;{% endif %}
        {% if posts.has_next %}<a href="{% url 'blog:page' posts.next_page_number %}">туда >></a>
        {% else %}<span class="disabled">туда >></span>{% endif %}
    </div>    
    {% endif %}               
{% endblock %}